/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface HelicopterBooking {
  'startTime' : string,
  'endTime' : string,
  'name' : string,
  'passengerCount' : bigint,
  'email' : string,
  'weights' : string,
  'notes' : string,
  'paymentMode' : string,
  'phone' : string,
}
export type SkillLevel = { 'intermediate' : null } |
  { 'beginner' : null } |
  { 'advanced' : null } |
  { 'expert' : null };
export type Sport = { 'basketball' : null } |
  { 'swimming' : null } |
  { 'soccer' : null } |
  { 'yoga' : null } |
  { 'cycling' : null } |
  { 'tennis' : null } |
  { 'running' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'primarySport' : Sport,
  'locationPermission' : boolean,
  'skillLevel' : SkillLevel,
  'profileComplete' : boolean,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'bookHelicopter' : ActorMethod<[HelicopterBooking], string>,
  'checkHelicopterAvailability' : ActorMethod<[string, string], string>,
  'completeProfile' : ActorMethod<
    [string, Sport, SkillLevel, boolean],
    UserProfile
  >,
  'getUserProfile' : ActorMethod<[], UserProfile>,
  'isProfileComplete' : ActorMethod<[], boolean>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];