/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const HelicopterBooking = IDL.Record({
  'startTime' : IDL.Text,
  'endTime' : IDL.Text,
  'name' : IDL.Text,
  'passengerCount' : IDL.Nat,
  'email' : IDL.Text,
  'weights' : IDL.Text,
  'notes' : IDL.Text,
  'paymentMode' : IDL.Text,
  'phone' : IDL.Text,
});
export const Sport = IDL.Variant({
  'basketball' : IDL.Null,
  'swimming' : IDL.Null,
  'soccer' : IDL.Null,
  'yoga' : IDL.Null,
  'cycling' : IDL.Null,
  'tennis' : IDL.Null,
  'running' : IDL.Null,
});
export const SkillLevel = IDL.Variant({
  'intermediate' : IDL.Null,
  'beginner' : IDL.Null,
  'advanced' : IDL.Null,
  'expert' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'primarySport' : Sport,
  'locationPermission' : IDL.Bool,
  'skillLevel' : SkillLevel,
  'profileComplete' : IDL.Bool,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'bookHelicopter' : IDL.Func([HelicopterBooking], [IDL.Text], []),
  'checkHelicopterAvailability' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'completeProfile' : IDL.Func(
      [IDL.Text, Sport, SkillLevel, IDL.Bool],
      [UserProfile],
      [],
    ),
  'getUserProfile' : IDL.Func([], [UserProfile], []),
  'isProfileComplete' : IDL.Func([], [IDL.Bool], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const HelicopterBooking = IDL.Record({
    'startTime' : IDL.Text,
    'endTime' : IDL.Text,
    'name' : IDL.Text,
    'passengerCount' : IDL.Nat,
    'email' : IDL.Text,
    'weights' : IDL.Text,
    'notes' : IDL.Text,
    'paymentMode' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Sport = IDL.Variant({
    'basketball' : IDL.Null,
    'swimming' : IDL.Null,
    'soccer' : IDL.Null,
    'yoga' : IDL.Null,
    'cycling' : IDL.Null,
    'tennis' : IDL.Null,
    'running' : IDL.Null,
  });
  const SkillLevel = IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
    'expert' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'primarySport' : Sport,
    'locationPermission' : IDL.Bool,
    'skillLevel' : SkillLevel,
    'profileComplete' : IDL.Bool,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'bookHelicopter' : IDL.Func([HelicopterBooking], [IDL.Text], []),
    'checkHelicopterAvailability' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'completeProfile' : IDL.Func(
        [IDL.Text, Sport, SkillLevel, IDL.Bool],
        [UserProfile],
        [],
      ),
    'getUserProfile' : IDL.Func([], [UserProfile], []),
    'isProfileComplete' : IDL.Func([], [IDL.Bool], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };