/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface http_header {
    value: string;
    name: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface HelicopterBooking {
    startTime: string;
    endTime: string;
    name: string;
    passengerCount: bigint;
    email: string;
    weights: string;
    notes: string;
    paymentMode: string;
    phone: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface UserProfile {
    name: string;
    primarySport: Sport;
    locationPermission: boolean;
    skillLevel: SkillLevel;
    profileComplete: boolean;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export enum SkillLevel {
    intermediate = "intermediate",
    beginner = "beginner",
    advanced = "advanced",
    expert = "expert"
}
export enum Sport {
    basketball = "basketball",
    swimming = "swimming",
    soccer = "soccer",
    yoga = "yoga",
    cycling = "cycling",
    tennis = "tennis",
    running = "running"
}
export interface backendInterface {
    bookHelicopter(booking: HelicopterBooking): Promise<string>;
    checkHelicopterAvailability(startTime: string, endTime: string): Promise<string>;
    completeProfile(name: string, sport: Sport, level: SkillLevel, locationPermission: boolean): Promise<UserProfile>;
    getUserProfile(): Promise<UserProfile>;
    isProfileComplete(): Promise<boolean>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { SkillLevel as _SkillLevel, Sport as _Sport, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async bookHelicopter(arg0: HelicopterBooking): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.bookHelicopter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookHelicopter(arg0);
            return result;
        }
    }
    async checkHelicopterAvailability(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.checkHelicopterAvailability(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkHelicopterAvailability(arg0, arg1);
            return result;
        }
    }
    async completeProfile(arg0: string, arg1: Sport, arg2: SkillLevel, arg3: boolean): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.completeProfile(arg0, to_candid_Sport_n1(this._uploadFile, this._downloadFile, arg1), to_candid_SkillLevel_n3(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_UserProfile_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeProfile(arg0, to_candid_Sport_n1(this._uploadFile, this._downloadFile, arg1), to_candid_SkillLevel_n3(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_UserProfile_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return from_candid_UserProfile_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return from_candid_UserProfile_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async isProfileComplete(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isProfileComplete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isProfileComplete();
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_SkillLevel_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SkillLevel): SkillLevel {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Sport_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Sport): Sport {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    primarySport: _Sport;
    locationPermission: boolean;
    skillLevel: _SkillLevel;
    profileComplete: boolean;
}): {
    name: string;
    primarySport: Sport;
    locationPermission: boolean;
    skillLevel: SkillLevel;
    profileComplete: boolean;
} {
    return {
        name: value.name,
        primarySport: from_candid_Sport_n7(_uploadFile, _downloadFile, value.primarySport),
        locationPermission: value.locationPermission,
        skillLevel: from_candid_SkillLevel_n9(_uploadFile, _downloadFile, value.skillLevel),
        profileComplete: value.profileComplete
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
} | {
    expert: null;
}): SkillLevel {
    return "intermediate" in value ? SkillLevel.intermediate : "beginner" in value ? SkillLevel.beginner : "advanced" in value ? SkillLevel.advanced : "expert" in value ? SkillLevel.expert : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    basketball: null;
} | {
    swimming: null;
} | {
    soccer: null;
} | {
    yoga: null;
} | {
    cycling: null;
} | {
    tennis: null;
} | {
    running: null;
}): Sport {
    return "basketball" in value ? Sport.basketball : "swimming" in value ? Sport.swimming : "soccer" in value ? Sport.soccer : "yoga" in value ? Sport.yoga : "cycling" in value ? Sport.cycling : "tennis" in value ? Sport.tennis : "running" in value ? Sport.running : value;
}
function to_candid_SkillLevel_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SkillLevel): _SkillLevel {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Sport_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sport): _Sport {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sport): {
    basketball: null;
} | {
    swimming: null;
} | {
    soccer: null;
} | {
    yoga: null;
} | {
    cycling: null;
} | {
    tennis: null;
} | {
    running: null;
} {
    return value == Sport.basketball ? {
        basketball: null
    } : value == Sport.swimming ? {
        swimming: null
    } : value == Sport.soccer ? {
        soccer: null
    } : value == Sport.yoga ? {
        yoga: null
    } : value == Sport.cycling ? {
        cycling: null
    } : value == Sport.tennis ? {
        tennis: null
    } : value == Sport.running ? {
        running: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SkillLevel): {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
} | {
    expert: null;
} {
    return value == SkillLevel.intermediate ? {
        intermediate: null
    } : value == SkillLevel.beginner ? {
        beginner: null
    } : value == SkillLevel.advanced ? {
        advanced: null
    } : value == SkillLevel.expert ? {
        expert: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
